version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db_alura
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: base
      MYSQL_USER: alura
      MYSQL_PASSWORD: alura
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
